In [44]:
import pandas as pd

In [45]:
starling_df = pd.read_excel('/Users/anast/Desktop/Statements/Starling.xlsx', sheet_name=None)

In [46]:
starling_df = pd.read_excel(
    r"C:\Users\anast\Desktop\Statements\Starling.xlsx",
    sheet_name=None
)

In [47]:
display(starling_df)

{'2024':           Date                   Counter Party         Reference  \
 0   2024-05-17                Sophia Anastacha               NaN
 1   2024-05-17                Sophia Anastacha  Sophia Anastacha
 2   2024-05-25                     S Anastacha  Monthly spending
 3   2024-05-26                    Tesco Petrol    TESCO PFS 3741
 4   2024-05-26                             B&Q        B & Q 1216
 ..         ...                             ...               ...
 178 2024-12-26         Sophia Anastacha Lloyds       credit card
 179 2024-12-26                     S Anastacha          TRANSFER
 180 2024-12-26  Sophia Anastacha & Guy Johnson      pets at home
 181 2024-12-26         Sophia Anastacha Lloyds       credit card
 182 2024-12-26                     S Anastacha          TRANSFER

                Type  Amount (GBP)  Balance (GBP) Spending Category  Notes
 0    FASTER PAYMENT        162.00         162.00            INCOME    NaN
 1    FASTER PAYMENT        260.13         422.13            INCOME    NaN
 2    FASTER PAYMENT        500.00         922.13            INCOME    NaN
 3        GOOGLE PAY        -37.64         884.49              FUEL    NaN
 4        GOOGLE PAY        -15.60         868.89          SHOPPING    NaN
 ..              ...           ...            ...               ...    ...
 178  FASTER PAYMENT        -47.30           0.00          PAYMENTS    NaN
 179  FASTER PAYMENT        700.00         700.00            INCOME    NaN
 180        TRANSFER         15.00         715.00            INCOME    NaN
 181  FASTER PAYMENT        -15.00         700.00          PAYMENTS    NaN
 182  FASTER PAYMENT        186.50         886.50            INCOME    NaN

 [183 rows x 8 columns],
 '2025':           Date                   Counter Party  \
 0   2025-01-01                   Starling Bank
 1   2025-01-03                Sophia Anastacha
 2   2025-01-03         Sophia Anastacha Lloyds
 3   2025-01-03         Sophia Anastacha Lloyds
 4   2025-01-05         Sophia Anastacha Lloyds
 ..         ...                             ...
 164 2025-12-30         Sophia Anastacha Lloyds
 165 2025-12-30                         Therapy
 166 2025-12-30                         Therapy
 167 2025-12-30         Sophia Anastacha Lloyds
 168 2025-12-30  Sophia Anastacha & Guy Johnson

                             Reference              Type  Amount (GBP)  \
 0            December Interest Earned  DEPOSIT INTEREST          1.88
 1    Transfer into Easy Saver Account          TRANSFER         -1.88
 2                         credit card    FASTER PAYMENT        -45.01
 3                         credit card    FASTER PAYMENT        -65.34
 4                         credit card    FASTER PAYMENT        -56.84
 ..                                ...               ...           ...
 164                          TRANSFER    FASTER PAYMENT        400.00
 165          Transfer into Easy Saver          TRANSFER        -82.50
 166          Transfer from Easy Saver          TRANSFER         82.50
 167                          transfer    FASTER PAYMENT       -187.69
 168                          Personal          TRANSFER        100.00

      Balance (GBP) Spending Category  Notes
 0           888.38            INCOME    NaN
 1           886.50            SAVING    NaN
 2           841.49          PAYMENTS    NaN
 3           776.15          PAYMENTS    NaN
 4           719.31          PAYMENTS    NaN
 ..             ...               ...    ...
 164         639.59            INCOME    NaN
 165         557.09            SAVING    NaN
 166         639.59            INCOME    NaN
 167         451.90          PAYMENTS    NaN
 168         551.90            INCOME    NaN

 [169 rows x 8 columns],
 '2026':          Date                   Counter Party               Reference  \
 0  2026-01-02         Sophia Anastacha Lloyds                transfer
 1  2026-01-04  Sophia Anastacha & Guy Johnson                    smol
 2  2026-01-04         Sophia Anastacha Lloyds                transfer
 3  2026-01-05         Sophia Anastacha Lloyds                 morvend
 4  2026-01-07              Amazon Marketplace  AMZNMktplace*ZC49H5ED4
 ..        ...                             ...                     ...
 92 2026-03-29              Jack's Gelato - Al  SQ *JACK'S GELATO - AL
 93 2026-03-29             Byron Covent Garden         BYRON CAMBRIDGE
 94 2026-03-29           John Lewis & Partners       JOHN LEWIS STORES
 95 2026-03-29         Sophia Anastacha Lloyds                  pecoro
 96 2026-03-30                        MiPermit            OBN*MiPermit

                  Type  Amount (GBP)  Balance (GBP) Spending Category  Notes
 0      FASTER PAYMENT       -100.00         451.90          PAYMENTS    NaN
 1            TRANSFER         12.50         464.40            INCOME    NaN
 2      FASTER PAYMENT        -12.50         451.90          PAYMENTS    NaN
 3      FASTER PAYMENT         -1.10         450.80          PAYMENTS    NaN
 4      ONLINE PAYMENT        -85.58         365.22          SHOPPING    NaN
 ..                ...           ...            ...               ...    ...
 92         GOOGLE PAY         -4.90         470.00        EATING_OUT    NaN
 93         GOOGLE PAY        -29.87         440.13        EATING_OUT    NaN
 94         GOOGLE PAY        -15.00         425.13          SHOPPING    NaN
 95     FASTER PAYMENT        -18.50         406.63          PAYMENTS    NaN
 96  CARD SUBSCRIPTION         -1.00         405.63         TRANSPORT    NaN

 [97 rows x 8 columns]}

In [48]:

starling_df = pd.concat(starling_df.values(), ignore_index=True)

In [49]:
display(starling_df)

,Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category,Notes
0,2024-05-17,Sophia Anastacha,NaN,FASTER PAYMENT,162.00,162.00,INCOME,NaN
1,2024-05-17,Sophia Anastacha,Sophia Anastacha,FASTER PAYMENT,260.13,422.13,INCOME,NaN
2,2024-05-25,S Anastacha,Monthly spending,FASTER PAYMENT,500.00,922.13,INCOME,NaN
3,2024-05-26,Tesco Petrol,TESCO PFS 3741,GOOGLE PAY,-37.64,884.49,FUEL,NaN
4,2024-05-26,B&Q,B & Q 1216,GOOGLE PAY,-15.60,868.89,SHOPPING,NaN
...,...,...,...,...,...,...,...,...
444,2026-03-29,Jack's Gelato - Al,SQ *JACK'S GELATO - AL,GOOGLE PAY,-4.90,470.00,EATING_OUT,NaN
445,2026-03-29,Byron Covent Garden,BYRON CAMBRIDGE,GOOGLE PAY,-29.87,440.13,EATING_OUT,NaN
446,2026-03-29,John Lewis & Partners,JOHN LEWIS STORES,GOOGLE PAY,-15.00,425.13,SHOPPING,NaN
447,2026-03-29,Sophia Anastacha Lloyds,pecoro,FASTER PAYMENT,-18.50,406.63,PAYMENTS,NaN
448,2026-03-30,MiPermit,OBN*MiPermit,CARD SUBSCRIPTION,-1.00,405.63,TRANSPORT,NaN

In [50]:
 starling_df.insert(1, 'Account', 'Starling')

In [51]:
display(starling_df)

,Date,Account,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category,Notes
0,2024-05-17,Starling,Sophia Anastacha,NaN,FASTER PAYMENT,162.00,162.00,INCOME,NaN
1,2024-05-17,Starling,Sophia Anastacha,Sophia Anastacha,FASTER PAYMENT,260.13,422.13,INCOME,NaN
2,2024-05-25,Starling,S Anastacha,Monthly spending,FASTER PAYMENT,500.00,922.13,INCOME,NaN
3,2024-05-26,Starling,Tesco Petrol,TESCO PFS 3741,GOOGLE PAY,-37.64,884.49,FUEL,NaN
4,2024-05-26,Starling,B&Q,B & Q 1216,GOOGLE PAY,-15.60,868.89,SHOPPING,NaN
...,...,...,...,...,...,...,...,...,...
444,2026-03-29,Starling,Jack's Gelato - Al,SQ *JACK'S GELATO - AL,GOOGLE PAY,-4.90,470.00,EATING_OUT,NaN
445,2026-03-29,Starling,Byron Covent Garden,BYRON CAMBRIDGE,GOOGLE PAY,-29.87,440.13,EATING_OUT,NaN
446,2026-03-29,Starling,John Lewis & Partners,JOHN LEWIS STORES,GOOGLE PAY,-15.00,425.13,SHOPPING,NaN
447,2026-03-29,Starling,Sophia Anastacha Lloyds,pecoro,FASTER PAYMENT,-18.50,406.63,PAYMENTS,NaN
448,2026-03-30,Starling,MiPermit,OBN*MiPermit,CARD SUBSCRIPTION,-1.00,405.63,TRANSPORT,NaN